group=com.adasjusk.killc
version=5.1
java_version=25
minecraft_version=26.2
paper_api_version=26.2.build.124-stable
api_version=26.2
velocity_version=4.2.0
loom_version=1.18.2
loader_version=0.19.5
fabric_api_version=0.160.0+26.2
shadow_version=9.6.1
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true