group=com.adasjusk.killc
version=5.1
java_version=25
minecraft_version=26.2
paper_api_version=26.2.build.26-alpha
spigot_api_version=26.2-R0.1-SNAPSHOT
velocity_version=3.4.0
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.152.2+26.2
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true