name: KillC
version: '4.0'
main: com.adasjusk.killc.KillC
author: adasjusk
api-version: 1.26
folia-supported: true
description: A plugin that adds kill commands for players with configurable options

commands:
  kill:
    description: Kills yourself or another player. Use "/kill reload" to reload config.
    usage: "/kill [player|@e[type=...]|reload]"
    permission: killc.self
    permission-message: "You don't have permission to use this command!"
  suicide:
    description: Kills yourself
    usage: "/suicide"
    permission: killc.self
    permission-message: "You don't have permission to use this command!"

permissions:
  killc.self:
    description: Allows using basic kill commands on yourself
    default: true
  killc.others:
    description: Allows killing other players
    default: op
  killc.selector:
    description: Allows using selectors like @e[type=...] (restricted to operators by default).
    default: op
  killc.reload:
    description: Allows reloading the plugin configuration
    default: op
  killc.*:
    description: Gives access to all KillC commands
    default: op
    children:
      killc.self: true
      killc.others: true
      killc.selector: true
      killc.reload: true